export const GET_ARTICLES_SUCCEEDED = 'GET_ARTICLES_SUCCEEDED';
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED';
export const GET_ARTICLES = 'GET_ARTICLES';

export const GET_AUTHORS_SUCCEEDED = 'GET_AUTHORS_SUCCEEDED';
export const GET_AUTHORS_FAILED = 'GET_AUTHORS_FAILED';
export const GET_AUTHORS = 'GET_AUTHORS';

export const PUT_ARTICLE_SUCCEEDED = 'PUT_ARTICLE_SUCCEEDED';
export const PUT_ARTICLE_FAILED = 'PUT_ARTICLE_FAILED';
export const PUT_ARTICLE = 'PUT_ARTICLE';

export const PUT_AUTHOR = 'PUT_AUTHOR';

export const SUBSCRIBE_CREATED_ARTICLE = 'SUBSCRIBE_CREATED_ARTICLE';
export const SUBSCRIBE_CREATED_ARTICLE_FAILED = 'SUBSCRIBE_CREATED_ARTICLE_FAILED';
export const SUBSCRIBE_CREATED_ARTICLE_SUCCEEDED = 'SUBSCRIBE_CREATED_ARTICLE_SUCCEEDED';
